---
title: "Homework Assignment 4"
subtitle: "Prioritizing potential aquaculture"
author: "IMS"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(terra)
library(sf)
library(tidyverse)
library(here)
library(tmap)
```


## Import Data

```{r}
WC_EEZ <- read_sf(here("data", "wc_regions_clean.shp"))

bath <- read_sf(here("data", "wc_regions_clean.shp"))
```

```{r}
SST_files <- list.files(
  here("data"), pattern = "average", 
  full.names = TRUE)

create_stack <- function(i){
  stack_layer <- rast(SST_files[i])
  return(stack_layer)
}

SST_stack <- c(create_stack(1), 
              create_stack(2), 
              create_stack(3), 
              create_stack(4), 
              create_stack(5))

names(SST_stack) <- c("2008", 
                    "2009", 
                    "2010", 
                    "2011", 
                    "2012")

```


```{r}
#| code-fold: true
#| code-summary: "Check if CRS of each dataset are equal, update if not"

if(st_crs(WC_EEZ) == st_crs(bath)) {
  print("Coordinate reference systems match")
} else{
  warning("Updating coordinate reference systems to match")
  # transform data to match
  WC_EEZ <- st_transform(WC_EEZ, st_crs(bath))
}
```


```{r}
#| code-fold: true
#| code-summary: "Check if CRS of each dataset are equal, update if not"

if(crs(SST_stack) == st_crs(bath)$wkt) {
  print("Coordinate reference systems match")
} else{
  warning("Updating coordinate reference systems to match")
  # transform data to match
  crs(SST_stack) <- st_crs(bath)$wkt
}
```


## Prepare Data